# Generated by Django 4.0.4 on 2022-09-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationNo', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Father', models.CharField(max_length=255)),
                ('Mother', models.CharField(max_length=255)),
                ('College', models.CharField(max_length=255)),
                ('Place', models.CharField(max_length=255)),
                ('Roll', models.CharField(max_length=255)),
                ('Group', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
            ],
        ),
    ]
